feign:
  client:
    config:
      default:
        connection-timeout: 1000
        read-timeout: 1000
        logger-level: full
      github-api:
        name: github-api
        url: https://api.github.com
        connectTimeout: 1000
        readTimeout: 1000
